feat add elasticsearch stack
pahud/cdk-soca pull request #84
Opened 2020-10-27 09:10 UTC by guorex

2020-10-27 10:49 UTC, pahud commented
Hi @guorex 

You probably need run `yarn upgrade` in this PR to update the yarn.lock file.

2020-10-27 11:01 UTC, pahud reviewed
LGTM

2020-10-27 12:18 UTC, guorex commented on src/analytics.ts
> +          version: es.ElasticsearchVersion.V7_4,
Ok, thanks for your suggestion

2020-10-28 23:11 UTC, pahud requested changes

2020-10-28 23:11 UTC, pahud commented on package.json
> +}
`yarn upgrade` will generate the trailing newline. You may run `npx projen` again to fix it.

2020-10-29 02:48 UTC, pahud approved these changes
Ship it!

2020-10-29 02:49 UTC, merged